# Configuration file for test.py

# Define locations of stellar config files, as well as input and output folders
# Only use '/' as path seperator, even on Windows systems
path_stellar_db: /DATA/stellar_db/
path_exoplanet_db: /DATA/exoplanetdb/
path_input_data: /DATA/ESO_Archive/
path_output_data: /DATA/output/
path_cache: /DATA/Cache/
path_exoSpectro: /DATA/exoSpectro/

# Specifics
name_target: K2-3
#name_target: HD209458
name_planet: d
dir_input: input
dir_output: output
dir_intermediary: intermediary
# Flag to recalculate everything, even if intermediary products exist
renew_all: false

#Path to molecfit executable
path_molecfit: ~/molecfit/bin/molecfit

# File names
# Those can be overwritten by the parameter file (in fact everything can)
psg_dir: PSG
psg_file_obs: radiance_*.csv
psg_file_phase: phases.txt
psg_file_star: flux.csv
psg_file_atm: planet.csv
psg_file_tell: tell.csv
psg_file: psg_config.txt

file_parameters: par.yaml
file_molecfit: molecfit.par

marcs_dir: MARCS
marcs_file_flux: 3896g4.7z-0.25m0.6t0.flx
marcs_file_ld: 3896g4.7z-0.25m0.6t0_{}.limb
marcs_ld_format: [1, 2, 3, 4, 5, 6, 7]
marcs_ld_interpolation_method: linear

ld_file: limb_darkening.fit
star_intensities: geom

harps_dir: HARPS
harps_calibration_dir: Calibration
harps_file_obs: '*.fits'
harps_file_tell: tell.txt
harps_file_sun: moon_2008-08-08_s1d.fits

harps_wl_mod: 10

# Intermediary data file
file_intermediary: intermediary.npz

# Output spectrum file name
file_spectrum: spectrum.png
file_data_out: solution.dat

# Setup
psg_wl_mod: 10000
#psg_flux_mod: 1.5e-17
marcs_flux_mod: 0.3184 #1/pi

parameters: stellar_db
flux: psg
intensities: limb_darkening
observation: psg
tellurics: psg

# For synthetic spectrum generation
snr: 1000                        # S/N (per spectral pixel per exposure) [S/NperResElem / sqrt(3) gives per pixel]"
n_exposures: 1                  # Number of individual exposures during entire transit
fwhm: 0.5                         # FWHM (instrumental profile approximated with gaussian)