# Configuration file for test.py

# Define locations of stellar config files, as well as input and output folders
# Only use '/' as path seperator, even on Windows systems
path_stellar_db: /DATA/stellar_db/
path_exoplanet_db: /DATA/exoplanetdb/
path_input_data: /DATA/ESO_Archive/
path_output_data: /DATA/output/
path_cache: /DATA/Cache/
path_exoSpectro: /DATA/exoSpectro/

# Specifics
name_target: K2-3
#name_target: HD209458
name_planet: d
dir_input: input
dir_output: output
dir_intermediary: intermediary
# Flag to recalculate everything, even if intermediary products exist
renew_all: false

#Path to molecfit executable
path_molecfit: ~/molecfit/bin/molecfit

# File names
# Those can be overwritten by the parameter file (in fact everything can)
dir_psg: PSG

file_obs_psg: radiance_*.csv
file_phase_psg: phases.txt
file_star_psg: flux.csv
file_atm_psg: planet.csv
file_tell_psg: tell.csv
file_psg: psg_config.txt

file_parameters: par.yaml
file_star_marcs: starF.flx
file_wl_marcs: flx_wavelengths.vac

file_molecfit: molecfit.par

marcs_dir: MARCS
marcs_file_ld: 3896g4.7z-0.25m0.6t0_{}.limb
marcs_ld_format: [1, 2, 3, 4, 5, 6, 7]
marcs_ld_interpolation_method: linear

ld_file: limb_darkening.fit
star_intensities: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

# Intermediary data file
file_intermediary: intermediary.npz

# Output spectrum file name
file_spectrum: spectrum.png
file_data_out: solution.dat

# Setup
psg_wl_mod: 10000
#psg_flux_mod: 1.5e-17
marcs_flux_mod: 1e-7

parameters: stellar_db
flux: psg
intensities: limb_darkening
observation: psg
tellurics: psg

# For synthetic spectrum generation
snr: 1000                        # S/N (per spectral pixel per exposure) [S/NperResElem / sqrt(3) gives per pixel]"
n_exposures: 1                  # Number of individual exposures during entire transit
fwhm: 0.5                         # FWHM (instrumental profile approximated with gaussian)