# Configuration file for test.py

# Define locations of stellar config files, as well as input and output folders
# Only use '/' as path seperator, even on Windows systems
path_stellar_db: /DATA/stellar_db/
path_exoplanet_db: /DATA/exoplanetdb/
path_input_data: /DATA/ESO_Archive/
path_output_data: /DATA/output/
path_cache: /DATA/Cache/
path_exoSpectro: /DATA/exoSpectro/

# Specifics
#name_target: K2-3
name_target: WASP-29
name_planet: b
dir_input: input
dir_output: output
dir_tmp: tmp
#Flag to recalculate everything, even if intermediary products exist
renew_all: false

#Path to molecfit executable
molecfit:
  path:  ~/molecfit/bin/molecfit
  file: molecfit.par

# File names
# Those can be overwritten by the parameter file (in fact everything can)
psg:
  dir: PSG
  file_obs: radiance_*.csv
  file_phase: phases.txt
  file_star: flux.csv
  file_atm: planet.csv
  file_tell: tell.csv
  file: psg_config.txt

file_parameters: par.yaml

marcs:
  dir: MARCS
  file_flux: 4000g4.7z-0.25m0.6t0.flx
  file_ld: 3896g4.7z-0.25m0.6t0_{}.limb
  ld_format: [1, 2, 3, 4, 5, 6, 7]
  ld_interpolation_method: linear

limb_darkening:
  file: limb_darkening.fit
  star_intensities: geom

harps:
  dir: HARPS
  calibration_dir: Calibration
  file_obs: '*.fits'
  file_tell: tell.txt
  file_sun: moon_2008-08-08_s1d.fits
  wl_mod: 1

idl:
  dir: SME
  file_solar: sol.dat
  file_sme: wasp29_4nlte.out
  file_obs: '*.ech'

# Intermediary data file
file_intermediary: intermediary.npz

# Output spectrum file name
file_spectrum: spectrum.png
file_data_out: solution.dat

# Setup
#psg_wl_mod: 10000
#psg_flux_mod: 1.5e-17
marcs_flux_mod: 0.3184 #1/pi

parameters: stellar_db
flux: psg
intensities: limb_darkening
observation: psg
tellurics: psg

# For synthetic spectrum generation
snr: 1000                        # S/N (per spectral pixel per exposure) [S/NperResElem / sqrt(3) gives per pixel]"
n_exposures: 1                  # Number of individual exposures during entire transit
fwhm: 0.5                         # FWHM (instrumental profile approximated with gaussian)
