# Configuration file for test.py

# Define locations of stellar config files, as well as input and output folders
# Only use '/' as path seperator, even on Windows systems
path_input_data: "../DATA/"
path_output_data: "../DATA/output/"

# Output spectrum file name
file_spectrum: spectrum.png
file_data_out: solution.dat

# TODO where to put this
broadening: 0

# The order in which modules are executed
workflow:
  - parameters
  - observations.wavelengths
  - planet
  - stellar_flux
  # - raw.awesimsoss
  # - reduction.pyreduce
  - intensities
  - observations
  - tellurics
   


# Modules to use
parameters: stellar_db   # StellarDB gets values from exoplanet.org
observations: synthetic   # JWST MIRI instrument (after data reduction)
tellurics: space         # No tellurics in space
stellar_flux: marcs    # Marcs Models, try out of transit observation instead?
intensities: claret2000  # Erik Aaronsons low resolution fitting
planet: psg
raw: awesimsoss
reduction: pyreduce


# Configurations for individual modules
stellar_db:
  path: /DATA/stellar_db/

pyreduce:
  telescope: JWST
  instrument: JWST_NIRISS
  mode: GR700XD
  base_dir: /DATA/{telescope}/NIRISS
  input_dir: awesimsoss
  output_dir: reduced
  filename: "*[0-9].ech"
  steps: ["bias", "flat", "norm_flat", "science", "finalize"]

nirspec:
  input_dir: "/DATA/Keck/NIRSPEC/{star}_{planet}"

molecfit:
  path:  ~/molecfit/bin/molecfit
  file: molecfit.par

psg:
  dir: /DATA/exoSpectro/{star}{planet}/input
  file_obs: radiance_*.csv
  file_phase: phases.txt
  file_star: flux.csv
  file_atm: planet.csv
  file_tell: tell.csv
  file_config: psg_config.txt

marcs:
  dir: /DATA/MARCS
  file_flux: 4000g4.7z-0.25m0.6t0.flx
  file_ld: 3896g4.7z-0.25m0.6t0_{}.limb
  ld_format: [1, 2, 3, 4, 5, 6, 7]
  ld_interpolation_method: linear

claret2000:
  file: claret2000.fits
  star_intensities: geom

harps:
  dir: HARPS
  calibration_dir: Calibration
  file_obs: '*.fits'
  file_tell: tell.txt
  file_sun: moon_2008-08-08_s1d.fits
  wl_mod: 1

awesimsoss:
  ngroups : 5
  nintegrations : 3
  nexposures : 1000
  dir : "/DATA/JWST/NIRISS/awesimsoss"
  fname : jwst_niriss_awesimsoss_{}.fits

idl:
  dir: SME
  file_solar: sol.dat
  file_sme: wasp29_4nlte.out
  file_obs: '*.ech'

synthetic:
  snr: 1000000                         # S/N (per spectral pixel per exposure) [S/NperResElem / sqrt(3) gives per pixel]"
  fwhm: 0.5                         # FWHM (instrumental profile approximated with gaussian)
  n_exposures: 60                   # Number of individual exposures during entire transit
  wavelength_minimum: 5000
  wavelength_maximum: 30000
  resolution: 100000

pandexo:
  instrument: "NIRSpec G395M"
  n_exposures: 500

wavelengths:
  wavelength_minimum: 5000
  wavelength_maximum: 30000
  resolution: 100000
  n_exposures: 60